global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'atc-daemons'
    static_configs:
      - targets: ['atc-dc1:8089', 'atc-dc2:8089']

  - job_name: 'consul-agents'
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['consul-dc1:8500', 'consul-dc2:8500']
